import React from 'react';
import { Track } from './TrackCard';

// Mock data for different moods
export const getMockRecommendations = (mood: string): Track[] => {
  const recommendations: Record<string, Track[]> = {
    happy: [
      {
        id: '1',
        title: 'Walking on Sunshine',
        artist: 'Katrina and the Waves',
        album: 'Walking on Sunshine',
        imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop',
        matchScore: 96,
        audioFeatures: {
          valence: 95,
          energy: 88,
          danceability: 78,
          tempo: 128,
        },
        reason: 'High valence and upbeat tempo perfectly match your happy mood',
      },
      {
        id: '2',
        title: 'Good Vibrations',
        artist: 'The Beach Boys',
        album: 'Smiley Smile',
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
        matchScore: 94,
        audioFeatures: {
          valence: 92,
          energy: 75,
          danceability: 65,
          tempo: 134,
        },
        reason: 'Classic feel-good vibes with positive emotional resonance',
      },
      {
        id: '3',
        title: 'Happy',
        artist: 'Pharrell Williams',
        album: 'G I R L',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop',
        matchScore: 93,
        audioFeatures: {
          valence: 96,
          energy: 80,
          danceability: 82,
          tempo: 160,
        },
        reason: 'Infectious positivity and danceable beat for your joyful state',
      },
    ],
    energetic: [
      {
        id: '4',
        title: 'Eye of the Tiger',
        artist: 'Survivor',
        album: 'Eye of the Tiger',
        imageUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400&h=400&fit=crop',
        matchScore: 97,
        audioFeatures: {
          valence: 65,
          energy: 94,
          danceability: 60,
          tempo: 109,
        },
        reason: 'Maximum energy and motivational power for your workout',
      },
      {
        id: '5',
        title: 'Thunderstruck',
        artist: 'AC/DC',
        album: 'The Razors Edge',
        imageUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&h=400&fit=crop',
        matchScore: 95,
        audioFeatures: {
          valence: 55,
          energy: 98,
          danceability: 45,
          tempo: 133,
        },
        reason: 'Explosive energy and driving rhythm to fuel your intensity',
      },
      {
        id: '6',
        title: 'Lose Yourself',
        artist: 'Eminem',
        album: '8 Mile Soundtrack',
        imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&h=400&fit=crop',
        matchScore: 93,
        audioFeatures: {
          valence: 60,
          energy: 92,
          danceability: 68,
          tempo: 171,
        },
        reason: 'Powerful beats and motivational lyrics match your energy',
      },
    ],
    romantic: [
      {
        id: '7',
        title: 'At Last',
        artist: 'Etta James',
        album: 'At Last!',
        imageUrl: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=400&h=400&fit=crop',
        matchScore: 98,
        audioFeatures: {
          valence: 75,
          energy: 35,
          danceability: 45,
          tempo: 75,
        },
        reason: 'Timeless romantic ballad with warm, loving sentiment',
      },
      {
        id: '8',
        title: 'Thinking Out Loud',
        artist: 'Ed Sheeran',
        album: 'x',
        imageUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&h=400&fit=crop',
        matchScore: 96,
        audioFeatures: {
          valence: 80,
          energy: 42,
          danceability: 78,
          tempo: 79,
        },
        reason: 'Sweet melody and loving lyrics for intimate moments',
      },
      {
        id: '9',
        title: 'Make You Feel My Love',
        artist: 'Adele',
        album: '19',
        imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&h=400&fit=crop',
        matchScore: 94,
        audioFeatures: {
          valence: 70,
          energy: 28,
          danceability: 35,
          tempo: 76,
        },
        reason: 'Heartfelt emotion and tender vocal delivery',
      },
    ],
    calm: [
      {
        id: '10',
        title: 'Weightless',
        artist: 'Marconi Union',
        album: 'Weightless',
        imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&h=400&fit=crop',
        matchScore: 99,
        audioFeatures: {
          valence: 50,
          energy: 12,
          danceability: 20,
          tempo: 60,
        },
        reason: 'Scientifically proven to reduce anxiety and promote relaxation',
      },
      {
        id: '11',
        title: 'Clair de Lune',
        artist: 'Claude Debussy',
        album: 'Suite bergamasque',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        matchScore: 97,
        audioFeatures: {
          valence: 55,
          energy: 15,
          danceability: 25,
          tempo: 66,
        },
        reason: 'Gentle piano melody creates peaceful atmosphere',
      },
      {
        id: '12',
        title: 'Holocene',
        artist: 'Bon Iver',
        album: 'Bon Iver',
        imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop',
        matchScore: 95,
        audioFeatures: {
          valence: 45,
          energy: 20,
          danceability: 30,
          tempo: 72,
        },
        reason: 'Serene vocals and ambient soundscape for tranquility',
      },
    ],
    sad: [
      {
        id: '13',
        title: 'Someone Like You',
        artist: 'Adele',
        album: '21',
        imageUrl: 'https://images.unsplash.com/photo-1534270804882-d328f2c30af2?w=400&h=400&fit=crop',
        matchScore: 96,
        audioFeatures: {
          valence: 25,
          energy: 35,
          danceability: 35,
          tempo: 67,
        },
        reason: 'Melancholic piano and emotional vocals resonate with sadness',
      },
      {
        id: '14',
        title: 'Hurt',
        artist: 'Johnny Cash',
        album: 'American IV: The Man Comes Around',
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
        matchScore: 94,
        audioFeatures: {
          valence: 20,
          energy: 30,
          danceability: 28,
          tempo: 81,
        },
        reason: 'Raw emotion and reflective lyrics for processing sorrow',
      },
      {
        id: '15',
        title: 'The Night We Met',
        artist: 'Lord Huron',
        album: 'Strange Trails',
        imageUrl: 'https://images.unsplash.com/photo-1458560871784-56d23406c091?w=400&h=400&fit=crop',
        matchScore: 92,
        audioFeatures: {
          valence: 30,
          energy: 38,
          danceability: 42,
          tempo: 137,
        },
        reason: 'Nostalgic melody captures longing and heartache',
      },
    ],
    focused: [
      {
        id: '16',
        title: 'Inception: Time',
        artist: 'Hans Zimmer',
        album: 'Inception OST',
        imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=400&fit=crop',
        matchScore: 97,
        audioFeatures: {
          valence: 40,
          energy: 45,
          danceability: 20,
          tempo: 76,
        },
        reason: 'Building intensity aids concentration without distraction',
      },
      {
        id: '17',
        title: 'Strobe',
        artist: 'deadmau5',
        album: 'For Lack of a Better Name',
        imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop',
        matchScore: 95,
        audioFeatures: {
          valence: 50,
          energy: 55,
          danceability: 48,
          tempo: 128,
        },
        reason: 'Progressive build maintains focus and productivity flow',
      },
      {
        id: '18',
        title: 'Avril 14th',
        artist: 'Aphex Twin',
        album: 'Drukqs',
        imageUrl: 'https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop',
        matchScore: 93,
        audioFeatures: {
          valence: 45,
          energy: 25,
          danceability: 30,
          tempo: 120,
        },
        reason: 'Minimal piano pattern creates focused mental space',
      },
    ],
    neutral: [
      {
        id: '19',
        title: 'The Less I Know The Better',
        artist: 'Tame Impala',
        album: 'Currents',
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
        matchScore: 90,
        audioFeatures: {
          valence: 60,
          energy: 62,
          danceability: 72,
          tempo: 116,
        },
        reason: 'Balanced energy and groove for any situation',
      },
      {
        id: '20',
        title: 'Electric Feel',
        artist: 'MGMT',
        album: 'Oracular Spectacular',
        imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop',
        matchScore: 88,
        audioFeatures: {
          valence: 65,
          energy: 68,
          danceability: 70,
          tempo: 104,
        },
        reason: 'Versatile indie-pop with universal appeal',
      },
      {
        id: '21',
        title: 'Do I Wanna Know?',
        artist: 'Arctic Monkeys',
        album: 'AM',
        imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop',
        matchScore: 86,
        audioFeatures: {
          valence: 55,
          energy: 58,
          danceability: 62,
          tempo: 85,
        },
        reason: 'Smooth rock rhythm works for any mood',
      },
    ],
    party: [
      {
        id: '22',
        title: 'Uptown Funk',
        artist: 'Mark Ronson ft. Bruno Mars',
        album: 'Uptown Special',
        imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&h=400&fit=crop',
        matchScore: 98,
        audioFeatures: {
          valence: 88,
          energy: 84,
          danceability: 92,
          tempo: 115,
        },
        reason: 'Infectious funk groove guaranteed to fill the dancefloor',
      },
      {
        id: '23',
        title: "Don't Stop Me Now",
        artist: 'Queen',
        album: 'Jazz',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop',
        matchScore: 96,
        audioFeatures: {
          valence: 90,
          energy: 88,
          danceability: 78,
          tempo: 156,
        },
        reason: 'High-energy anthem with unstoppable party spirit',
      },
      {
        id: '24',
        title: 'September',
        artist: 'Earth, Wind & Fire',
        album: 'The Best of Earth, Wind & Fire Vol. 1',
        imageUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&h=400&fit=crop',
        matchScore: 95,
        audioFeatures: {
          valence: 92,
          energy: 82,
          danceability: 88,
          tempo: 126,
        },
        reason: 'Timeless disco-funk classic perfect for celebration',
      },
    ],
  };

  return recommendations[mood] || recommendations.neutral;
};
